### ISSUE TITLE
name="file" forced in the post method

### ISSUE THREAD

**Issue by thetravis** [AckerApple/angular-file#11]
Angular-file doesn't seem to care about the set name property of input.

On front side I have 
>    \<input type="file" ngf name="singleFile" (filesChange)="uploader.uploadFiles($event)" /\>
>    \<ngfUploader [(ref)]="uploader" [options]="{url:'/upload'}"\>\</ngfUploader\>

and on the server side I have Multer trying to catch file with field "singleFile"

>    var upload = multer({ dest: 'tmp/' });
>    app.post('/upload', upload.single('singleFile'), function (req, res, next) { ... } );

It doesn't work even though the field names are matched. If I change 
> upload.single('singleFile')

to

> upload.single('file')

it magically works!

Trying to send random.file and checking browser's console network tab I notice the post request has
> Content-Disposition: form-data; name="file"; filename="random.file"
> Content-Type: application/json

regardless what I type in name="singleFile" property.

**Comment by AckerApple** [comment]
Great idea on the surface but it won't be done. Both this package and the one I forked it from, are not reading the file input name. Sooooooo hard to explain...

It's become so standard to just send the file as input post name "file" but that's not the answer to your question nor is it the reason I won't be adding your request.

You do already have an option available to you as such:

```
<ngfUploader [(ref)]="uploader" [options]="{url:'/upload', forceFilename:'singleFile'}"></ngfUploader>
```

Most all of us who are balls deep in this project, think ngfUploader and ANY file transmission process is NOT the responsibility of this project INCLUDING what name is on an input. YOU SHOULD be using the HTML5 FormData class to add and make transmission of files, which also allows you to set the name of inputs being transmitted. YOU SHOULD be using Angular http or httpclient, not ngfUploader.

Sorry for the confusion, some of us want to rip ngfUploader completely out of this project for the confusion and hassle of maintaining an HTTP transmitter which already exists in Angular and is far better.

To close, ngFileUploader transmits multiple files as individual requests instead of one mass request like with Angular Http and HttpClient....... It's not recommended, please stop using ngfUploader as you are encouraging us further to remove it.

Thank you kindly

**Comment by AckerApple** [comment]
#12 was created from out of this issue report

**Comment by figuerres** [comment]
i think that is the right thing, remove the old upload stuff totally, have the demo code and the markdown page and any demo site just show the new HttpClient  method.

**Comment by AckerApple** [comment]
@figuerres, I think you are so right even as I've tried playing devils advocate for this request...

All my Http requests go through just one service. NOT one service and this little package that has an ngfUploader TEMPLATE-TO-TRANSMISSION component.

I like things simple too but this package is over extending itself and helping people go down the wrong path.

**Comment by thetravis** [comment]
@AckerApple You're right. I'm not sure, but it seems it's WebKitFormBoundary that puts the name="file" in the request. As you mention, same thing happens with the old ng2-file-upload. 

As I'm rather new to web development it took me whole workday to figure out where the problem was as their back-end example doesn't work. Might not be in the scope of this plugin but I'd like to see (request) a working back-end example. 

Anyway, I need more control over the transmission so I was going to switch to the HttpClient method as soon as I get the back-end working right. 

I agree that you should remove ngFileUploader.

**Comment by AckerApple** [comment]
Excellent feedback. Much appreciated.
