### ISSUE TITLE
Not allowing xls format for accepted files

### ISSUE THREAD

**Issue by soniar4i** [AckerApple/angular-file#23]
Hi @AckerApple,

first of all, thanks for this awesome development! It's very very helpful :) but I'm facing an issue today, when trying to set the accept format file for xls files it doesn't work, maybe I'm doing something wrong or I'm using the wrong name, right now I'm doing:

    accept = 'application/pdf, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';

Thanks in advance for your help!

**Comment by soniar4i** [comment]
Sorry, closing my own question! I thought the file format was the mime tipy not the .extension like .xls

Thanks again for your awesome tool! :)

**Comment by AckerApple** [comment]
You can use either definition type

Please star, follow, or perform any other social actions that may naturally improve the popularity of this package

Thank you extra kindly

**Comment by soniar4i** [comment]
Hi! 
The weirdest thing is that it is not working when I add application/vnd.openxmlformats-officedocument.spreadsheetml.sheet it's like I added accept = '*' to the component. 

I thought it was because I have to use  "angular-file": "0.3.8" but also tried with the new version (even if I can't use it) and it doesn't work for me either.

Can you please help me on this. 

Thanks!

**Comment by figuerres** [comment]
i think you might have the wrong mime type name, vnd  means vendor specific  
this is a pain but look here:
https://www.iana.org/assignments/media-types/media-types.xhtml
and if the file is ".xls"  then that is the older microsoft binary file format *NOT* the open standard xml format.
also see here:
https://stackoverflow.com/questions/974079/setting-mime-type-for-excel-document

**Comment by AckerApple** [comment]
Yeah what figuerres says.

I say that because your mime type is way too long and different machines are not always going to have that mime type of "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet".

I suggest you use multiple mime types and even extension separated by a comma.

ALSO! On the demo page for [angular-file](https://ackerapple.github.io/angular-file/), AFTER you select a file the mime type is displayed in the list of files. Compare what you expect with what mime type is actually seen in the list of files
