### ISSUE TITLE
SE

### ISSUE THREAD

**Issue by ganggangxu** [AckerApple/angular-file#24]
Hi, I installed the package and my angular/core is 5.2.6. But after include the ngfModule into ngmodules, I got issue called "Can't resolve all parameters for ***" and if I removed this module, my app works fine. Is anyone have idea?

**Comment by AckerApple** [comment]
Yourbissue report is too generic. Sound like you haven’t got based the import steps so something in your basic setup is most likely wrong.

I would try updating to a current release of Angular but I’m certain a basic setup step has not been performed correctly.

Package is in production and used by too many for a basic import issue to exist

**Comment by shahvarun93** [comment]
Even I am facing the same issue, it works for the first time but when I rebuild the application it gives me the error Can't resolve all parameters for ***. I followed same steps as mentioned in your repository but it still gives me the same error. How should I resolve this error?

**Comment by figuerres** [comment]
@shahvarun93  and @ganggangxu 
please list more details. for example  are both of you using angular 5.2.6 ?
are you building with angular cli or with another method ?
is the error actually saying "***"  or something else ?

an error like this can come from missing needed polyfills or from missing an @injectable directive in a ts file.

**Comment by shahvarun93** [comment]
I am not using angular-cli and *** is indeed name of the component and yes the version of angular is 5.2.6.

**Comment by AckerApple** [comment]
I've stopped using webpack altogether going on 2 months now, for Angular projects.

I use angular-cli as seen here in code: https://github.com/AckerApple/angular-file/blob/development/package.json#L55

I highly advise you to get off webpack as life is made much easier by Angular. I understand this is far easier said than done but someone told me just the same and it is true.

Sorry fellas, I do not have the issue you are having and again this package is in production. I will not be going out of my way to test webpack, if thats even where the issue lies.

I've even had issue reports with plunker examples that work. Ya'll gotta be doing something different, highly doubt its webpack but it could be which is why i stopped using it.

**Comment by figuerres** [comment]
to all:

Angular CLI uses webpack internally, they just take care of running it and manage the parameters.
Angular CLI can also make a smaller run-time bundle as it can do advanced optimizing of the code.

also the "***" is very odd... i did a google and did not find that, just related issues where the "***" was something else.

**Comment by AckerApple** [comment]
Denny, your participation and help in this package is greatly appreciated. I have added you as a collaborator. I fully trust you with this package.

Thank you extra kindly good guy. Happy to have you aboard

**Comment by figuerres** [comment]
thanks, i have been head down for a while but not gone....
at work we just got thru the release of a major part of the project i have been working on for just over 2 years. we took a task that had been an all day job and cut the time in half and made a lot of improvements. we had about 2 months of nailing down lose ends and testing and  starting the first set of users, finding a few bugs and updating the code....  we now have a week where we are not seeing a any new issues and we are starting the next module to release .....
