### ISSUE TITLE
postName in ngfFormData for multiple files

### ISSUE THREAD

**Issue by webplease** [AckerApple/angular-file#56]
Hi,

i'm trying to send more the 1 file to backend (PHP) with ngfDrop (multiple=1) but the server receives only 1 file ... 

I solve replacing postName="file" with postName="file[]" in the relative ngfFormData.

Is it normal?

**Comment by AckerApple** [comment]
There are two bindings for getting a file or multiple files ... [(file)] and [(files)]

If you already knew that, that I have no other guesses at this time and would require examples.

This package has long since been used in production by many without hearing of something like what you are short-hand trying to report.

**Comment by webplease** [comment]
very strange ... with [(file)] i can manage only 1 file (not an array of files). With [(files)] works, the headers of request seems to be OK, but on PHP side the server receives an array with only 1 element ... (with var_dump($_FILES[]).

Same if i create a simple HTML page:

<form action="post.php" method="post" enctype="multipart/form-data">
  <input type="file" name="file[]"  multiple="multiple"/>
  <button type="submit">Submit</button>
</form>

In <input> name must be "file[]" and not "file" to receive the array of multiple files.
