### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by yossely** [AckerApple/angular-file#66]
Hi! congrats for your package!

I realized that you have your package's built in the repo, but where's the source code? 

without it, how can I contribute?

**Comment by AckerApple** [comment]
TIP: Be sure to checkout available branches before working on a repo. Often the default package is the distributed code in order to make it easier to be installed.

This package has the default branch as the distributed code so npm install can be used without declaring the branch since the install branch is the default.

Here is the source code:
https://github.com/AckerApple/angular-file/tree/development
